version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmaster_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: taskmaster_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  
###
### version for docker compose
### services
### image - posgres db on alpine 15 linux machine
### should not production enviroment variables put like this, they go in .env file(.env is in .gitignore)
### ports left is for my pc, and right is for container
### volumes - place where we store data on container permanently
### restart - run until I say otherwise
###
### commands:  
### Pokreni bazu
### docker-compose up -d
###
### Vidi da li radi
### docker ps
###
### Zaustavi bazu
### docker-compose down
###
### Zaustavi i OBRIŠI podatke (volume)
### docker-compose down -v
###
### Vidi logove
### docker-compose logs postgres
###
### Uði u bazu (psql terminal)
### docker exec -it taskmaster_db psql -U postgres -d taskmaster_dev